version: "3"

services:
    nginx:
        build:
            context: .
            dockerfile: ./nginx/Dockerfile
            args:
                SRC_DIR: ${SRC_DIR}
                PROJECT_DIR: ${PROJECT_DIR}
                IMAGE_VERSION: ${IMAGE_VERSION}
        ports:
            - "${FRONTEND_PORT}:80"
        volumes:
            - "./${SRC_DIR}:${PROJECT_DIR}"
        env_file:
            - .env
        depends_on:
            - php-fpm
    php-fpm:
        build:
            context: .
            dockerfile: ./php-fpm/Dockerfile
            args:
                SRC_DIR: ${SRC_DIR}
                PROJECT_DIR: ${PROJECT_DIR}
        command: /bin/sh -c "composer install --ignore-platform-reqs && php-fpm"
        volumes:
            - "./${SRC_DIR}:${PROJECT_DIR}"
        env_file:
            - .env
    mongodb:
        image: mongo:3.7.5
        volumes:
            - ./mongodb/data:/data/db
