version: "3"

services:
    php-fpm:
        image: project-php-dev
        volumes:
            - ./code:/data/projects/project
        deploy:
            mode: replicated
            replicas: 1
    nginx:
        image: project-nginx
        volumes:
            - ./code:/data/projects/project
        ports:
            - "27030:8080"
    mongodb:
        image: mongo:latest
        volumes:
            - ./mongodb/data:/data/db