version: "3"

services:
    nginx:
        build: ./nginx/.
        ports:
            - "${FRONTEND_PORT}:80"
        volumes:
            - "./${SRC_DIR}:${PROJECT_DIR}"
        env_file:
            - .env
        depends_on:
            - php-fpm
    php-fpm:
        build: ./php/.
        command: /bin/sh -c "composer install --ignore-platform-reqs && php-fpm"
        working_dir: "${PROJECT_DIR}"
        volumes:
            - "./${SRC_DIR}:${PROJECT_DIR}"
        env_file:
            - .env
    mongodb:
        image: mongo:3.7.5
        volumes:
            - ./mongodb/data:/data/db

# examples
    # command
        # bundle exec thin -p 3000
        # ["bundle", "exec", "thin", "-p", "3000"]
        # ["composer", "install", "--ignore-platform-reqs", "&&", "php-fpm"]