version: "3"

services:
    php-fpm:
        image: project-php-prod
        deploy:
            mode: replicated
            replicas: 2
    nginx:
        image: project-nginx
        ports:
            - "27030:8080"
    mongodb:
        image: mongo:latest
        volumes:
            - ./mongodb/data:/data/db