version: "3"

services:
    php-fpm:
        image: php:7.1.4-fpm
        volumes:
            - ./code:/data/projects/project
        deploy:
            mode: replicated
            replicas: 1
    nginx:
        image: project-nginx
        volumes:
            - ./code:/data/projects/project
        ports:
            - "27030:8080"
